#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
	mode http
	balance roundrobin
	server 2502-web-01 35.227.96.101:80 check
	server 2502-web-02 34.73.223.7:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
