#!/usr/bin/env bash
# displays "bad luck from China" for the 4th, "bad luck from Japan" for the 9th, and "bad luck from Italy" for the 17th iteration
i=1

while [ $i -le 20 ]
do
	echo $i
	case $i in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	i=$(( i+1 ))
done
